//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.5.1.0 (NJsonSchema v9.4.10.0) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace Janitra.Bot.Api
{
#pragma warning disable // Disable all warnings

	[System.CodeDom.Compiler.GeneratedCode("NSwag", "11.5.1.0")]
	public partial interface IClient
	{
		/// <summary>Get the list of all Citra Builds that are being actively tested</summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		System.Threading.Tasks.Task<System.Collections.Generic.List<JsonCitraBuild>> ApiCitraBuildsListGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

		/// <summary>List all of the RomMovieResults for the given janitraBot</summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		System.Threading.Tasks.Task<System.Collections.Generic.List<JsonRomMovieResult>> ApiRomMovieResultsListGetAsync(int? janitraBotId = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		System.Threading.Tasks.Task ApiRomMovieResultsAddPostAsync(NewRomMovieResult movieResult = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

		/// <summary>Gets a list of all movies for the given rom that are actively testing</summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		System.Threading.Tasks.Task<System.Collections.Generic.List<JsonRomMovie>> ApiRomMoviesListByRomIdGetAsync(int romId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

		/// <summary>Get a list of all of the commercial roms that tests are performed against</summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		System.Threading.Tasks.Task<System.Collections.Generic.List<JsonRom>> ApiRomsListGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

		/// <summary>Get a list of all TestDefinitions that are being actively tested</summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		System.Threading.Tasks.Task<System.Collections.Generic.List<JsonTestDefinition>> ApiTestDefinitionsListGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

		/// <summary>Get all of the test results for the given Build, TestDefinition, JanitraBot. Ordered by TestDefinitionId, JanitraBotId</summary>
		/// <param name="janitraBotId">What JanitraBot to fetch TestResults for</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		System.Threading.Tasks.Task<System.Collections.Generic.List<JsonTestResult>> ApiTestResultsListGetAsync(int? janitraBotId = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

		/// <summary>Submit a test result</summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		System.Threading.Tasks.Task ApiTestResultsAddPostAsync(NewTestResult testResult = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

	}

	[System.CodeDom.Compiler.GeneratedCode("NSwag", "11.5.1.0")]
	public partial class Client : IClient
	{
		private System.Lazy<Newtonsoft.Json.JsonSerializerSettings> _settings;
		private string _baseUrl = "";

		public Client(string baseUrl)
		{
			BaseUrl = baseUrl;
			_settings = new System.Lazy<Newtonsoft.Json.JsonSerializerSettings>(() =>
			{
				var settings = new Newtonsoft.Json.JsonSerializerSettings();
				UpdateJsonSerializerSettings(settings);
				return settings;
			});
		}

		public string BaseUrl
		{
			get { return _baseUrl; }
			set { _baseUrl = value; }
		}

		partial void UpdateJsonSerializerSettings(Newtonsoft.Json.JsonSerializerSettings settings);
		partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, string url);
		partial void PrepareRequest(System.Net.Http.HttpClient client, System.Net.Http.HttpRequestMessage request, System.Text.StringBuilder urlBuilder);
		partial void ProcessResponse(System.Net.Http.HttpClient client, System.Net.Http.HttpResponseMessage response);

		/// <summary>Get the list of all Citra Builds that are being actively tested</summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		public async System.Threading.Tasks.Task<System.Collections.Generic.List<JsonCitraBuild>> ApiCitraBuildsListGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
		{
			var urlBuilder_ = new System.Text.StringBuilder();
			urlBuilder_.Append(BaseUrl).Append("/api/citra-builds/list");

			var client_ = new System.Net.Http.HttpClient();
			try
			{
				using (var request_ = new System.Net.Http.HttpRequestMessage())
				{
					request_.Method = new System.Net.Http.HttpMethod("GET");
					request_.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

					PrepareRequest(client_, request_, urlBuilder_);
					var url_ = urlBuilder_.ToString();
					request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
					PrepareRequest(client_, request_, url_);

					var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
					try
					{
						var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
						foreach (var item_ in response_.Content.Headers)
							headers_[item_.Key] = item_.Value;

						ProcessResponse(client_, response_);

						var status_ = ((int)response_.StatusCode).ToString();
						if (status_ == "200")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							var result_ = default(System.Collections.Generic.List<JsonCitraBuild>);
							try
							{
								result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.List<JsonCitraBuild>>(responseData_, _settings.Value);
								return result_;
							}
							catch (System.Exception exception)
							{
								throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
							}
						}
						else
						if (status_ != "200" && status_ != "204")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							throw new SwaggerException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", status_, responseData_, headers_, null);
						}

						return default(System.Collections.Generic.List<JsonCitraBuild>);
					}
					finally
					{
						if (response_ != null)
							response_.Dispose();
					}
				}
			}
			finally
			{
				if (client_ != null)
					client_.Dispose();
			}
		}

		/// <summary>List all of the RomMovieResults for the given janitraBot</summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		public async System.Threading.Tasks.Task<System.Collections.Generic.List<JsonRomMovieResult>> ApiRomMovieResultsListGetAsync(int? janitraBotId = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
		{
			var urlBuilder_ = new System.Text.StringBuilder();
			urlBuilder_.Append(BaseUrl).Append("/api/rom-movie-results/list?");
			if (janitraBotId != null) urlBuilder_.Append("janitraBotId=").Append(System.Uri.EscapeDataString(System.Convert.ToString(janitraBotId.Value, System.Globalization.CultureInfo.InvariantCulture))).Append("&");
			urlBuilder_.Length--;

			var client_ = new System.Net.Http.HttpClient();
			try
			{
				using (var request_ = new System.Net.Http.HttpRequestMessage())
				{
					request_.Method = new System.Net.Http.HttpMethod("GET");
					request_.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

					PrepareRequest(client_, request_, urlBuilder_);
					var url_ = urlBuilder_.ToString();
					request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
					PrepareRequest(client_, request_, url_);

					var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
					try
					{
						var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
						foreach (var item_ in response_.Content.Headers)
							headers_[item_.Key] = item_.Value;

						ProcessResponse(client_, response_);

						var status_ = ((int)response_.StatusCode).ToString();
						if (status_ == "200")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							var result_ = default(System.Collections.Generic.List<JsonRomMovieResult>);
							try
							{
								result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.List<JsonRomMovieResult>>(responseData_, _settings.Value);
								return result_;
							}
							catch (System.Exception exception)
							{
								throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
							}
						}
						else
						if (status_ != "200" && status_ != "204")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							throw new SwaggerException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", status_, responseData_, headers_, null);
						}

						return default(System.Collections.Generic.List<JsonRomMovieResult>);
					}
					finally
					{
						if (response_ != null)
							response_.Dispose();
					}
				}
			}
			finally
			{
				if (client_ != null)
					client_.Dispose();
			}
		}

		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		public async System.Threading.Tasks.Task ApiRomMovieResultsAddPostAsync(NewRomMovieResult movieResult = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
		{
			var urlBuilder_ = new System.Text.StringBuilder();
			urlBuilder_.Append(BaseUrl).Append("/api/rom-movie-results/add");

			var client_ = new System.Net.Http.HttpClient();
			try
			{
				using (var request_ = new System.Net.Http.HttpRequestMessage())
				{
					var content_ = new System.Net.Http.StringContent(Newtonsoft.Json.JsonConvert.SerializeObject(movieResult, _settings.Value));
					content_.Headers.ContentType.MediaType = "application/json";
					request_.Content = content_;
					request_.Method = new System.Net.Http.HttpMethod("POST");

					PrepareRequest(client_, request_, urlBuilder_);
					var url_ = urlBuilder_.ToString();
					request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
					PrepareRequest(client_, request_, url_);

					var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
					try
					{
						var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
						foreach (var item_ in response_.Content.Headers)
							headers_[item_.Key] = item_.Value;

						ProcessResponse(client_, response_);

						var status_ = ((int)response_.StatusCode).ToString();
						if (status_ == "200")
						{
							return;
						}
						else
						if (status_ != "200" && status_ != "204")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							throw new SwaggerException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", status_, responseData_, headers_, null);
						}
					}
					finally
					{
						if (response_ != null)
							response_.Dispose();
					}
				}
			}
			finally
			{
				if (client_ != null)
					client_.Dispose();
			}
		}

		/// <summary>Gets a list of all movies for the given rom that are actively testing</summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		public async System.Threading.Tasks.Task<System.Collections.Generic.List<JsonRomMovie>> ApiRomMoviesListByRomIdGetAsync(int romId, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
		{
			if (romId == null)
				throw new System.ArgumentNullException("romId");

			var urlBuilder_ = new System.Text.StringBuilder();
			urlBuilder_.Append(BaseUrl).Append("/api/rom-movies/list/{romId}");
			urlBuilder_.Replace("{romId}", System.Uri.EscapeDataString(System.Convert.ToString(romId, System.Globalization.CultureInfo.InvariantCulture)));

			var client_ = new System.Net.Http.HttpClient();
			try
			{
				using (var request_ = new System.Net.Http.HttpRequestMessage())
				{
					request_.Method = new System.Net.Http.HttpMethod("GET");
					request_.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

					PrepareRequest(client_, request_, urlBuilder_);
					var url_ = urlBuilder_.ToString();
					request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
					PrepareRequest(client_, request_, url_);

					var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
					try
					{
						var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
						foreach (var item_ in response_.Content.Headers)
							headers_[item_.Key] = item_.Value;

						ProcessResponse(client_, response_);

						var status_ = ((int)response_.StatusCode).ToString();
						if (status_ == "200")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							var result_ = default(System.Collections.Generic.List<JsonRomMovie>);
							try
							{
								result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.List<JsonRomMovie>>(responseData_, _settings.Value);
								return result_;
							}
							catch (System.Exception exception)
							{
								throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
							}
						}
						else
						if (status_ != "200" && status_ != "204")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							throw new SwaggerException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", status_, responseData_, headers_, null);
						}

						return default(System.Collections.Generic.List<JsonRomMovie>);
					}
					finally
					{
						if (response_ != null)
							response_.Dispose();
					}
				}
			}
			finally
			{
				if (client_ != null)
					client_.Dispose();
			}
		}

		/// <summary>Get a list of all of the commercial roms that tests are performed against</summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		public async System.Threading.Tasks.Task<System.Collections.Generic.List<JsonRom>> ApiRomsListGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
		{
			var urlBuilder_ = new System.Text.StringBuilder();
			urlBuilder_.Append(BaseUrl).Append("/api/roms/list");

			var client_ = new System.Net.Http.HttpClient();
			try
			{
				using (var request_ = new System.Net.Http.HttpRequestMessage())
				{
					request_.Method = new System.Net.Http.HttpMethod("GET");
					request_.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

					PrepareRequest(client_, request_, urlBuilder_);
					var url_ = urlBuilder_.ToString();
					request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
					PrepareRequest(client_, request_, url_);

					var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
					try
					{
						var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
						foreach (var item_ in response_.Content.Headers)
							headers_[item_.Key] = item_.Value;

						ProcessResponse(client_, response_);

						var status_ = ((int)response_.StatusCode).ToString();
						if (status_ == "200")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							var result_ = default(System.Collections.Generic.List<JsonRom>);
							try
							{
								result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.List<JsonRom>>(responseData_, _settings.Value);
								return result_;
							}
							catch (System.Exception exception)
							{
								throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
							}
						}
						else
						if (status_ != "200" && status_ != "204")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							throw new SwaggerException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", status_, responseData_, headers_, null);
						}

						return default(System.Collections.Generic.List<JsonRom>);
					}
					finally
					{
						if (response_ != null)
							response_.Dispose();
					}
				}
			}
			finally
			{
				if (client_ != null)
					client_.Dispose();
			}
		}

		/// <summary>Get a list of all TestDefinitions that are being actively tested</summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		public async System.Threading.Tasks.Task<System.Collections.Generic.List<JsonTestDefinition>> ApiTestDefinitionsListGetAsync(System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
		{
			var urlBuilder_ = new System.Text.StringBuilder();
			urlBuilder_.Append(BaseUrl).Append("/api/test-definitions/list");

			var client_ = new System.Net.Http.HttpClient();
			try
			{
				using (var request_ = new System.Net.Http.HttpRequestMessage())
				{
					request_.Method = new System.Net.Http.HttpMethod("GET");
					request_.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

					PrepareRequest(client_, request_, urlBuilder_);
					var url_ = urlBuilder_.ToString();
					request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
					PrepareRequest(client_, request_, url_);

					var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
					try
					{
						var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
						foreach (var item_ in response_.Content.Headers)
							headers_[item_.Key] = item_.Value;

						ProcessResponse(client_, response_);

						var status_ = ((int)response_.StatusCode).ToString();
						if (status_ == "200")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							var result_ = default(System.Collections.Generic.List<JsonTestDefinition>);
							try
							{
								result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.List<JsonTestDefinition>>(responseData_, _settings.Value);
								return result_;
							}
							catch (System.Exception exception)
							{
								throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
							}
						}
						else
						if (status_ != "200" && status_ != "204")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							throw new SwaggerException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", status_, responseData_, headers_, null);
						}

						return default(System.Collections.Generic.List<JsonTestDefinition>);
					}
					finally
					{
						if (response_ != null)
							response_.Dispose();
					}
				}
			}
			finally
			{
				if (client_ != null)
					client_.Dispose();
			}
		}

		/// <summary>Get all of the test results for the given Build, TestDefinition, JanitraBot. Ordered by TestDefinitionId, JanitraBotId</summary>
		/// <param name="janitraBotId">What JanitraBot to fetch TestResults for</param>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		public async System.Threading.Tasks.Task<System.Collections.Generic.List<JsonTestResult>> ApiTestResultsListGetAsync(int? janitraBotId = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
		{
			var urlBuilder_ = new System.Text.StringBuilder();
			urlBuilder_.Append(BaseUrl).Append("/api/test-results/list?");
			if (janitraBotId != null) urlBuilder_.Append("janitraBotId=").Append(System.Uri.EscapeDataString(System.Convert.ToString(janitraBotId.Value, System.Globalization.CultureInfo.InvariantCulture))).Append("&");
			urlBuilder_.Length--;

			var client_ = new System.Net.Http.HttpClient();
			try
			{
				using (var request_ = new System.Net.Http.HttpRequestMessage())
				{
					request_.Method = new System.Net.Http.HttpMethod("GET");
					request_.Headers.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));

					PrepareRequest(client_, request_, urlBuilder_);
					var url_ = urlBuilder_.ToString();
					request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
					PrepareRequest(client_, request_, url_);

					var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
					try
					{
						var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
						foreach (var item_ in response_.Content.Headers)
							headers_[item_.Key] = item_.Value;

						ProcessResponse(client_, response_);

						var status_ = ((int)response_.StatusCode).ToString();
						if (status_ == "200")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							var result_ = default(System.Collections.Generic.List<JsonTestResult>);
							try
							{
								result_ = Newtonsoft.Json.JsonConvert.DeserializeObject<System.Collections.Generic.List<JsonTestResult>>(responseData_, _settings.Value);
								return result_;
							}
							catch (System.Exception exception)
							{
								throw new SwaggerException("Could not deserialize the response body.", status_, responseData_, headers_, exception);
							}
						}
						else
						if (status_ != "200" && status_ != "204")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							throw new SwaggerException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", status_, responseData_, headers_, null);
						}

						return default(System.Collections.Generic.List<JsonTestResult>);
					}
					finally
					{
						if (response_ != null)
							response_.Dispose();
					}
				}
			}
			finally
			{
				if (client_ != null)
					client_.Dispose();
			}
		}

		/// <summary>Submit a test result</summary>
		/// <param name="cancellationToken">A cancellation token that can be used by other objects or threads to receive notice of cancellation.</param>
		/// <returns>Success</returns>
		/// <exception cref="SwaggerException">A server side error occurred.</exception>
		public async System.Threading.Tasks.Task ApiTestResultsAddPostAsync(NewTestResult testResult = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
		{
			var urlBuilder_ = new System.Text.StringBuilder();
			urlBuilder_.Append(BaseUrl).Append("/api/test-results/add");

			var client_ = new System.Net.Http.HttpClient();
			try
			{
				using (var request_ = new System.Net.Http.HttpRequestMessage())
				{
					var content_ = new System.Net.Http.StringContent(Newtonsoft.Json.JsonConvert.SerializeObject(testResult, _settings.Value));
					content_.Headers.ContentType.MediaType = "application/json";
					request_.Content = content_;
					request_.Method = new System.Net.Http.HttpMethod("POST");

					PrepareRequest(client_, request_, urlBuilder_);
					var url_ = urlBuilder_.ToString();
					request_.RequestUri = new System.Uri(url_, System.UriKind.RelativeOrAbsolute);
					PrepareRequest(client_, request_, url_);

					var response_ = await client_.SendAsync(request_, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
					try
					{
						var headers_ = System.Linq.Enumerable.ToDictionary(response_.Headers, h_ => h_.Key, h_ => h_.Value);
						foreach (var item_ in response_.Content.Headers)
							headers_[item_.Key] = item_.Value;

						ProcessResponse(client_, response_);

						var status_ = ((int)response_.StatusCode).ToString();
						if (status_ == "200")
						{
							return;
						}
						else
						if (status_ != "200" && status_ != "204")
						{
							var responseData_ = await response_.Content.ReadAsStringAsync().ConfigureAwait(false);
							throw new SwaggerException("The HTTP status code of the response was not expected (" + (int)response_.StatusCode + ").", status_, responseData_, headers_, null);
						}
					}
					finally
					{
						if (response_ != null)
							response_.Dispose();
					}
				}
			}
			finally
			{
				if (client_ != null)
					client_.Dispose();
			}
		}

	}



	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public partial class JsonCitraBuild
	{
		[Newtonsoft.Json.JsonProperty("citraBuildId", Required = Newtonsoft.Json.Required.Always)]
		public int CitraBuildId { get; set; }

		[Newtonsoft.Json.JsonProperty("gitHash", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public string GitHash { get; set; }

		[Newtonsoft.Json.JsonProperty("commitTime", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public System.DateTimeOffset CommitTime { get; set; }

		[Newtonsoft.Json.JsonProperty("buildType", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		[Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
		public JsonCitraBuildBuildType BuildType { get; set; }

		[Newtonsoft.Json.JsonProperty("dateAdded", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public System.DateTimeOffset DateAdded { get; set; }

		[Newtonsoft.Json.JsonProperty("windowsUrl", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
		public string WindowsUrl { get; set; }

		[Newtonsoft.Json.JsonProperty("linuxUrl", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
		public string LinuxUrl { get; set; }

		[Newtonsoft.Json.JsonProperty("osxUrl", Required = Newtonsoft.Json.Required.Default, NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore)]
		public string OsxUrl { get; set; }

		public string ToJson()
		{
			return Newtonsoft.Json.JsonConvert.SerializeObject(this);
		}

		public static JsonCitraBuild FromJson(string data)
		{
			return Newtonsoft.Json.JsonConvert.DeserializeObject<JsonCitraBuild>(data);
		}
	}

	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public partial class JsonRomMovieResult
	{
		[Newtonsoft.Json.JsonProperty("romMovieResultId", Required = Newtonsoft.Json.Required.Always)]
		public int RomMovieResultId { get; set; }

		[Newtonsoft.Json.JsonProperty("citraBuildId", Required = Newtonsoft.Json.Required.Always)]
		public int CitraBuildId { get; set; }

		[Newtonsoft.Json.JsonProperty("romMovieId", Required = Newtonsoft.Json.Required.Always)]
		public int RomMovieId { get; set; }

		[Newtonsoft.Json.JsonProperty("reportedAt", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public System.DateTimeOffset ReportedAt { get; set; }

		public string ToJson()
		{
			return Newtonsoft.Json.JsonConvert.SerializeObject(this);
		}

		public static JsonRomMovieResult FromJson(string data)
		{
			return Newtonsoft.Json.JsonConvert.DeserializeObject<JsonRomMovieResult>(data);
		}
	}

	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public partial class NewRomMovieResult
	{
		/// <summary>JanitraBot Token</summary>
		[Newtonsoft.Json.JsonProperty("accessKey", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public string AccessKey { get; set; }

		[Newtonsoft.Json.JsonProperty("citraBuildId", Required = Newtonsoft.Json.Required.Always)]
		public int CitraBuildId { get; set; }

		[Newtonsoft.Json.JsonProperty("romMovieId", Required = Newtonsoft.Json.Required.Always)]
		public int RomMovieId { get; set; }

		[Newtonsoft.Json.JsonProperty("janitraBotId", Required = Newtonsoft.Json.Required.Always)]
		public int JanitraBotId { get; set; }

		[Newtonsoft.Json.JsonProperty("executionResult", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		[Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
		public NewRomMovieResultExecutionResult ExecutionResult { get; set; }

		[Newtonsoft.Json.JsonProperty("log", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public byte[] Log { get; set; }

		[Newtonsoft.Json.JsonProperty("screenshots", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public System.Collections.Generic.List<NewScreenshot> Screenshots { get; set; } = new System.Collections.Generic.List<NewScreenshot>();

		public string ToJson()
		{
			return Newtonsoft.Json.JsonConvert.SerializeObject(this);
		}

		public static NewRomMovieResult FromJson(string data)
		{
			return Newtonsoft.Json.JsonConvert.DeserializeObject<NewRomMovieResult>(data);
		}
	}

	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public partial class NewScreenshot
	{
		[Newtonsoft.Json.JsonProperty("frameNumber", Required = Newtonsoft.Json.Required.Always)]
		public int FrameNumber { get; set; }

		[Newtonsoft.Json.JsonProperty("topImage", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public byte[] TopImage { get; set; }

		[Newtonsoft.Json.JsonProperty("bottomImage", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public byte[] BottomImage { get; set; }

		public string ToJson()
		{
			return Newtonsoft.Json.JsonConvert.SerializeObject(this);
		}

		public static NewScreenshot FromJson(string data)
		{
			return Newtonsoft.Json.JsonConvert.DeserializeObject<NewScreenshot>(data);
		}
	}

	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public partial class JsonRomMovie
	{
		[Newtonsoft.Json.JsonProperty("romMovieId", Required = Newtonsoft.Json.Required.Always)]
		public int RomMovieId { get; set; }

		[Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public string Name { get; set; }

		[Newtonsoft.Json.JsonProperty("romId", Required = Newtonsoft.Json.Required.Always)]
		public int RomId { get; set; }

		[Newtonsoft.Json.JsonProperty("movieUrl", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public string MovieUrl { get; set; }

		[Newtonsoft.Json.JsonProperty("movieSha256", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public string MovieSha256 { get; set; }

		/// <summary>The system region that Citra will use during emulation</summary>
		[Newtonsoft.Json.JsonProperty("citraRegionValue", Required = Newtonsoft.Json.Required.Always)]
		public int CitraRegionValue { get; set; }

		public string ToJson()
		{
			return Newtonsoft.Json.JsonConvert.SerializeObject(this);
		}

		public static JsonRomMovie FromJson(string data)
		{
			return Newtonsoft.Json.JsonConvert.DeserializeObject<JsonRomMovie>(data);
		}
	}

	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public partial class JsonRom
	{
		[Newtonsoft.Json.JsonProperty("romId", Required = Newtonsoft.Json.Required.Always)]
		public int RomId { get; set; }

		/// <summary>In the format: Game Name (Region)</summary>
		[Newtonsoft.Json.JsonProperty("name", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public string Name { get; set; }

		[Newtonsoft.Json.JsonProperty("romType", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		[Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
		public JsonRomRomType RomType { get; set; }

		[Newtonsoft.Json.JsonProperty("addedByUserId", Required = Newtonsoft.Json.Required.Always)]
		public int AddedByUserId { get; set; }

		[Newtonsoft.Json.JsonProperty("romFileName", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public string RomFileName { get; set; }

		/// <summary>Hex encoded sha256 hash value of the ROM (Lowercase)</summary>
		[Newtonsoft.Json.JsonProperty("romSha256", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		[System.ComponentModel.DataAnnotations.StringLength(64, MinimumLength = 64)]
		public string RomSha256 { get; set; }

		public string ToJson()
		{
			return Newtonsoft.Json.JsonConvert.SerializeObject(this);
		}

		public static JsonRom FromJson(string data)
		{
			return Newtonsoft.Json.JsonConvert.DeserializeObject<JsonRom>(data);
		}
	}

	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public partial class JsonTestDefinition
	{
		[Newtonsoft.Json.JsonProperty("testDefinitionId", Required = Newtonsoft.Json.Required.Always)]
		public int TestDefinitionId { get; set; }

		[Newtonsoft.Json.JsonProperty("testName", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public string TestName { get; set; }

		/// <summary>Url the movie can be downloaded from</summary>
		[Newtonsoft.Json.JsonProperty("movieUrl", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public string MovieUrl { get; set; }

		[Newtonsoft.Json.JsonProperty("movieSha256", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public string MovieSha256 { get; set; }

		[Newtonsoft.Json.JsonProperty("addedAt", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public System.DateTimeOffset AddedAt { get; set; }

		[Newtonsoft.Json.JsonProperty("testRom", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public JsonTestRom TestRom { get; set; } = new JsonTestRom();

		public string ToJson()
		{
			return Newtonsoft.Json.JsonConvert.SerializeObject(this);
		}

		public static JsonTestDefinition FromJson(string data)
		{
			return Newtonsoft.Json.JsonConvert.DeserializeObject<JsonTestDefinition>(data);
		}
	}

	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public partial class JsonTestRom
	{
		[Newtonsoft.Json.JsonProperty("testRomId", Required = Newtonsoft.Json.Required.Always)]
		public int TestRomId { get; set; }

		[Newtonsoft.Json.JsonProperty("romUrl", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public string RomUrl { get; set; }

		[Newtonsoft.Json.JsonProperty("romSha256", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public string RomSha256 { get; set; }

		public string ToJson()
		{
			return Newtonsoft.Json.JsonConvert.SerializeObject(this);
		}

		public static JsonTestRom FromJson(string data)
		{
			return Newtonsoft.Json.JsonConvert.DeserializeObject<JsonTestRom>(data);
		}
	}

	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public partial class JsonTestResult
	{
		[Newtonsoft.Json.JsonProperty("testResultId", Required = Newtonsoft.Json.Required.Always)]
		public int TestResultId { get; set; }

		[Newtonsoft.Json.JsonProperty("citraBuildId", Required = Newtonsoft.Json.Required.Always)]
		public int CitraBuildId { get; set; }

		[Newtonsoft.Json.JsonProperty("testDefinitionId", Required = Newtonsoft.Json.Required.Always)]
		public int TestDefinitionId { get; set; }

		[Newtonsoft.Json.JsonProperty("reportedAt", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public System.DateTimeOffset ReportedAt { get; set; }

		public string ToJson()
		{
			return Newtonsoft.Json.JsonConvert.SerializeObject(this);
		}

		public static JsonTestResult FromJson(string data)
		{
			return Newtonsoft.Json.JsonConvert.DeserializeObject<JsonTestResult>(data);
		}
	}

	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public partial class NewTestResult
	{
		/// <summary>JanitraBot Token</summary>
		[Newtonsoft.Json.JsonProperty("accessKey", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public string AccessKey { get; set; }

		[Newtonsoft.Json.JsonProperty("citraBuildId", Required = Newtonsoft.Json.Required.Always)]
		public int CitraBuildId { get; set; }

		[Newtonsoft.Json.JsonProperty("janitraBotId", Required = Newtonsoft.Json.Required.Always)]
		public int JanitraBotId { get; set; }

		[Newtonsoft.Json.JsonProperty("testDefinitionId", Required = Newtonsoft.Json.Required.Always)]
		public int TestDefinitionId { get; set; }

		[Newtonsoft.Json.JsonProperty("log", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public byte[] Log { get; set; }

		[Newtonsoft.Json.JsonProperty("screenshotTop", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public byte[] ScreenshotTop { get; set; }

		[Newtonsoft.Json.JsonProperty("screenshotBottom", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		public byte[] ScreenshotBottom { get; set; }

		[Newtonsoft.Json.JsonProperty("executionResult", Required = Newtonsoft.Json.Required.Always)]
		[System.ComponentModel.DataAnnotations.Required]
		[Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
		public NewTestResultExecutionResult ExecutionResult { get; set; }

		[Newtonsoft.Json.JsonProperty("timeTakenSeconds", Required = Newtonsoft.Json.Required.Always)]
		public double TimeTakenSeconds { get; set; }

		public string ToJson()
		{
			return Newtonsoft.Json.JsonConvert.SerializeObject(this);
		}

		public static NewTestResult FromJson(string data)
		{
			return Newtonsoft.Json.JsonConvert.DeserializeObject<NewTestResult>(data);
		}
	}

	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public enum JsonCitraBuildBuildType
	{
		[System.Runtime.Serialization.EnumMember(Value = "Custom")]
		Custom = 0,

		[System.Runtime.Serialization.EnumMember(Value = "CitraMaster")]
		CitraMaster = 1,

		[System.Runtime.Serialization.EnumMember(Value = "CitraPullRequest")]
		CitraPullRequest = 2,

	}

	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public enum NewRomMovieResultExecutionResult
	{
		[System.Runtime.Serialization.EnumMember(Value = "Crash")]
		Crash = 0,

		[System.Runtime.Serialization.EnumMember(Value = "Completed")]
		Completed = 1,

		[System.Runtime.Serialization.EnumMember(Value = "Timeout")]
		Timeout = 2,

	}

	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public enum JsonRomRomType
	{
		[System.Runtime.Serialization.EnumMember(Value = "Cartridge")]
		Cartridge = 0,

		[System.Runtime.Serialization.EnumMember(Value = "SystemApplication")]
		SystemApplication = 1,

		[System.Runtime.Serialization.EnumMember(Value = "EShop")]
		EShop = 2,

		[System.Runtime.Serialization.EnumMember(Value = "VirtualConsole")]
		VirtualConsole = 3,

	}

	[System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "9.4.10.0")]
	public enum NewTestResultExecutionResult
	{
		[System.Runtime.Serialization.EnumMember(Value = "Crash")]
		Crash = 0,

		[System.Runtime.Serialization.EnumMember(Value = "Completed")]
		Completed = 1,

		[System.Runtime.Serialization.EnumMember(Value = "Timeout")]
		Timeout = 2,

	}

	[System.CodeDom.Compiler.GeneratedCode("NSwag", "11.5.1.0")]
	public class SwaggerException : System.Exception
	{
		public string StatusCode { get; private set; }

		public string Response { get; private set; }

		public System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>> Headers { get; private set; }

		public SwaggerException(string message, string statusCode, string response, System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>> headers, System.Exception innerException)
			: base(message, innerException)
		{
			StatusCode = statusCode;
			Response = response;
			Headers = headers;
		}

		public override string ToString()
		{
			return string.Format("HTTP Response: \n\n{0}\n\n{1}", Response, base.ToString());
		}
	}

	[System.CodeDom.Compiler.GeneratedCode("NSwag", "11.5.1.0")]
	public class SwaggerException<TResult> : SwaggerException
	{
		public TResult Result { get; private set; }

		public SwaggerException(string message, string statusCode, string response, System.Collections.Generic.Dictionary<string, System.Collections.Generic.IEnumerable<string>> headers, TResult result, System.Exception innerException)
			: base(message, statusCode, response, headers, innerException)
		{
			Result = result;
		}
	}

}